### ISSUE TITLE
404 error on our Homepage

### ISSUE THREAD

**Issue by PkCEBC** [iCaspar/arras#22]
Our website team discovered our webpage is displaying a Site showing 500 Internal Server Error.  When we spoke to our hosting company, they responded that they discovered there "is an issue with your theme /var/www/html/wordpress/wp-content/themes/arras-theme that is causing a 404 error to show on your home page. "

I hope you might have some insight as to what might be wrong.  Thank you.

FYI Our site is www.cebc.net/wordpress

**Comment by iCaspar** [comment]
I've taken a quick look at your site, and it appears that whatever had been causing the 500 Internal Server Error has been cleared up. However, you seem to have several other issues going on, including the 404 Not Found error you mention. But in addition, you have lots of files -- both theme and plug-in files -- that are not loading. Almost as if your entire `/wp-content/` folder is missing from your WordPress installation. Perhaps your hosting company removed the folder (or files in the folder) in an effort to clear up the 500 error or perhaps it was corrupted before they got involved in a way that was causing the 500 error. Hard to say. And, given that the homepage is also returning "not found" you may have lost some entries in your WordPress database as well.

Such file and/or database corruption is not typical. It may be someone's having made an innocent mistake when adjusting your hosting or WordPress settings, or it could be due to your site having been hacked.

At this point, I'd recommend getting someone familiar with WordPress to take a thorough look at your WordPress installation and database, as the problem goes beyond just your Arras theme.

**Comment by PkCEBC** [comment]
Thanks for you insight. We will do as you have suggested.
