### ISSUE TITLE
Homepage has lost all taxonomy terms for featured post areas

### ISSUE THREAD

**Issue by AlexLockwood74** [iCaspar/arras#59]
Hi, been happily using Arras theme for a long while now, over two years, and today when I logged in I noticed my different home page featured post sections have lost all of their taxonomy terms for pulling from selected categories, which is probably the most useful thing in Arras for me. 

Site is alexlockwood.co.uk, using Wordpress 4.9.1 on own-hosted platform. Any help?

**Comment by iCaspar** [comment]
@AlexLockwood74 it looks like you have project-ar2 (Arras 2.x) on that site. We have not made any changes at all affecting Arras 2. Is it possible that a plugin or other update has caused the taxonomy terms settings to be lost? Are you able to reset them?

**Comment by iCaspar** [comment]
Unfortunately, at the moment there is no update available from Arras 2. I would _not_ recommend using Arras 3. If you can reset the taxonomy terms from the Appearance > Options page, I'd go with that first. What's puzzling is the "all-of-a-sudden" nature of their being dropped, since apparently, nothing else on the site had changed.

If the taxonomy term selections are not available at all on the options page, that's even more curious. In that case, if you could attach a screenshot of what you see on your options page, that may be helpful as a first step toward figuring it out.

**Comment by AlexLockwood74** [comment]
Ive reset all option settings, which has reset things like homepage layout. The other thing that has changed is that previously the tabs General | Home | Layout etc used to click through to different pages, but now (again 'all of a sudden') are simply like basic anchor links down the same page. The Taxonomy > Terms fields still don't work. Used to be search fields where typing in the first few words of a category would show them up for selection, now nothing, see attached.
<img width="1044" alt="screen shot 2017-12-19 at 14 39 32" src="https://user-images.githubusercontent.com/34676754/34162232-de229440-e4ca-11e7-8042-d2dc514b8b82.png">

**Comment by iCaspar** [comment]
@AlexLockwood74: Thanks for the screenshot.

The Import/Export section should have always been there. The information there is showing that the terms are empty. But why?

I can replicate the issue on a test install by setting

`define( 'SCRIPT_DEBUG', true );`

in the WP `config.php` file. But whether that is the case on your live site, you would have to check... and if so, how it got there is the question, because nothing in Arras or any legitimate reason should SCRIPT_DEBUG be true on a live site. So that's the first thing to check.

That said, it looks like Arras 2.0 has a bug in the theme's `/library/admin/admin.php` file:

![screen shot 2017-12-19 at 11 01 17 am](https://user-images.githubusercontent.com/7462998/34166538-2a3162a8-e4ad-11e7-87ec-f3c08b31f426.png)

should be

![screen shot 2017-12-19 at 11 01 55 am](https://user-images.githubusercontent.com/7462998/34166557-368595e2-e4ad-11e7-8481-cb30f69bb2d2.png)

So the second thing would be to change there `ar-theme-options` to `jquery-tokeninput` and see if that will resolve the issue. Here is a corrected version of the file (please make a backup of your current admin.php file just in case): https://gist.github.com/iCaspar/ca06fc46fc0ca08a1c9d4969c45bfdfa

**Comment by AlexLockwood74** [comment]
Thanks Caspar, I've uploaded the new admin.php file and that has fixed it, the taxonomies are now showing correctly. All fine. Although I certainly did *not* edit the admin.php file though so don't know what caused it. Anyway, thanks. And looking forward to seeing Arras move forward.

**Comment by iCaspar** [comment]
Glad it's worked out for you.

**Comment by AlexLockwood74** [comment]
The Options Tabs are now working out properly. The only thing missing is the Design options, there's no option now to change to left/right sidebar

<img width="914" alt="screen shot 2017-12-20 at 16 40 34" src="https://user-images.githubusercontent.com/34676754/34217882-9b476f4e-e5a4-11e7-9408-94560f8df23b.png">

But dont worry if you're super busy this is not a major problem for me.
