### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by psycholyzern** [iCaspar/arras#61]
I downloaded the theme via release page and using git.
Both have the same issue. They are trying to load `wp-content/themes/arras/assets/dist/css/default.min.css?ver=1.8`

The problem is, this file does not exist.

**Comment by iCaspar** [comment]
@psycholyzern Very strange. I've checked the zip package on the [arrastheme.net download page](https://arrastheme.net/downloads/), and the file is in there.

Here's a zip with that default.min.css file, if you want to unzip it and FTP it into that directory:
[default.min.css.zip](https://github.com/iCaspar/arras/files/1875947/default.min.css.zip)

(It's not in the git version, since it's generated from other source files.)

**Comment by psycholyzern** [comment]
Hi iCaspar. Thanks. I downloaded from the first link and it is working fine. But, no support for custom post type? It only display default post type.

**Comment by psycholyzern** [comment]
My bad. There is a menu to select which post type I want to display. Thanks a lot😁.
